using System.Globalization;

namespace SoundDeviceSwitcher.App.Localization;

public sealed class LocalizationService
{
    private readonly Dictionary<string, string> _english = new(StringComparer.Ordinal)
    {
        ["AppName"] = "SoundDeviceSwitcher",
        ["SidebarMenuTitle"] = "Menu",
        ["MainTab"] = "Main",
        ["SettingsTab"] = "Settings",
        ["ActionsGroup"] = "Quick actions",
        ["GeneralGroup"] = "General",
        ["AutomationGroup"] = "Automation",
        ["LanguageLabel"] = "Language",
        ["ThemeLabel"] = "Theme",
        ["StartWithWindowsLabel"] = "Start at Windows startup",
        ["StartMinimizedAtStartupLabel"] = "Start minimized at system startup",
        ["MinimizeToTrayOnCloseLabel"] = "Minimize to tray when closing",
        ["EnableUpdateNotificationsLabel"] = "Notify about app updates",
        ["SyncCommunicationDeviceWithPlaybackLabel"] = "Sync communications with playback",
        ["AutoSwitchToNewPlaybackDeviceLabel"] = "Auto-switch when new device connects",
        ["DeviceAIconLabel"] = "Notification icon",
        ["DeviceBIconLabel"] = "Device B icon",
        ["ThemeModeSystem"] = "System",
        ["ThemeModeLight"] = "Light",
        ["ThemeModeDark"] = "Dark",
        ["DevicesGroup"] = "Devices",
        ["DeviceALabel"] = "Device A",
        ["DeviceBLabel"] = "Device B",
        ["HotkeyGroup"] = "Shortcuts",
        ["OverlayGroup"] = "Overlay",
        ["ProfilesGroup"] = "Profiles",
        ["EnableProfilesLabel"] = "Program-priority auto-switching",
        ["ProfileAutomationHint"] = "Automatically applies a profile based on the active program. Profiles higher in the list take priority.",
        ["EnableGlobalHotkey"] = "Enable global shortcut",
        ["SwitchShortcutSectionLabel"] = "Device switch",
        ["EnableOverlayHotkeyLabel"] = "Enable overlay shortcut",
        ["OverlayShortcutSectionLabel"] = "Overlay shortcut",
        ["RecentUndoSectionLabel"] = "Undo recent switch",
        ["EnableRecentSwitchUndoHotkeyLabel"] = "Enable recent switch undo shortcut",
        ["ModifiersLabel"] = "Modifiers",
        ["KeyLabel"] = "Key",
        ["HotkeyHint"] = "Set the shortcuts you want to use while the app is running. They work globally, including when the app is hidden in the tray.",
        ["ShortcutCapturePlaceholder"] = "Click here and press a shortcut",
        ["RecentSwitchUndoHint"] = "Press within 5 seconds of the most recent output, input, or communications device change to swap back.",
        ["OverlayPositionLabel"] = "Overlay position",
        ["OverlayLayoutLabel"] = "Layout direction",
        ["OverlayLayoutHorizontal"] = "Horizontal",
        ["OverlayLayoutVertical"] = "Vertical",
        ["OverlayHeightLabel"] = "Overlay height (% of screen)",
        ["OverlayHint"] = "Uses the profiles on this page. Choose the overlay position, layout, size, and shortcut.",
        ["OpenProfileOverlayButton"] = "Open overlay",
        ["ProfileNameLabel"] = "Profile name",
        ["ProfileIconLabel"] = "Profile icon",
        ["ProfilePriorityLabel"] = "Order",
        ["ProfileOutputDeviceLabel"] = "Output device",
        ["ProfileInputDeviceLabel"] = "Input device",
        ["ProfileProgramsLabel"] = "Programs",
        ["ProfileOrderHint"] = "Profiles higher in the list take priority when program-priority auto-switching is enabled.",
        ["ToggleNowButton"] = "Toggle now",
        ["RefreshDevicesButton"] = "Refresh devices",
        ["OpenIconFolderButton"] = "Open icon folder",
        ["RefreshIconsButton"] = "Refresh icons",
        ["CreateToggleShortcutButton"] = "Create toggle shortcut",
        ["AddProfileButton"] = "Add profile",
        ["RemoveProfileButton"] = "Remove profile",
        ["MoveProfileUpButton"] = "Move up",
        ["MoveProfileDownButton"] = "Move down",
        ["AddProgramButton"] = "Add program",
        ["RemoveProgramButton"] = "Remove program",
        ["InitialStatus"] = "Choose two playback devices. Changes are saved automatically.",
        ["LoadedSavedSettings"] = "Loaded your saved settings.",
        ["NoSavedSettings"] = "No saved settings yet. Choose two devices to get started.",
        ["ProfileDefaultName"] = "Profile {0}",
        ["ProfileUnnamed"] = "Unnamed profile",
        ["ProfileDoNotChangeOption"] = "Do not change",
        ["SelectProgramsDialogTitle"] = "Select program executables",
        ["StatusSettingsSaved"] = "Settings saved.",
        ["StatusCreatedShortcut"] = "Created toggle shortcut: {0}",
        ["StatusLanguageChanged"] = "Language updated.",
        ["StatusThemeChanged"] = "Theme updated.",
        ["StatusProfileApplied"] = "Applied profile: {0}",
        ["StatusRecentSwitchUndoApplied"] = "Restored the recent audio device state.",
        ["StatusUpdateAvailable"] = "A new update is available: {0}",
        ["StatusMinimizedToTray"] = "The app is still running in the system tray.",
        ["StatusOpenedIconFolder"] = "Opened the icon folder.",
        ["StatusIconsRefreshed"] = "Reloaded {0} icon files from the built-in and custom icon folders.",
        ["StatusNoIconsFound"] = "No selectable icons were found in the built-in or custom icon folders.",
        ["ErrorNeedTwoPlaybackDevices"] = "Connect at least two playback devices to continue.",
        ["ErrorPrimarySecondaryDifferent"] = "Device A and Device B must be different.",
        ["ErrorEnableModifier"] = "Enable at least one modifier key for the shortcut.",
        ["ErrorNoConfig"] = "No saved configuration was found. Open the app and choose your device settings first.",
        ["ErrorCouldNotLoadConfig"] = "Could not load the saved configuration: {0}",
        ["ErrorEmptyConfig"] = "The saved configuration file is empty.",
        ["ErrorCouldNotReadAudioDevices"] = "Windows audio devices could not be read. HRESULT: {0}. {1}",
        ["ErrorAppCouldNotLoad"] = "The app could not finish loading.",
        ["ErrorGlobalHotkeyUnavailable"] = "The shortcut could not be registered. Another app may already be using it.",
        ["ErrorProfileMissingDevices"] = "Profile '{0}' could not be applied because these devices are unavailable: {1}",
        ["ErrorRecentSwitchUndoUnavailable"] = "No recent device change is available to undo.",
        ["ErrorRecentSwitchUndoExpired"] = "The recent device change can only be undone within 5 seconds.",
        ["ErrorRecentSwitchUndoMissingDevices"] = "The recent audio state could not be restored because these devices are unavailable: {0}",
        ["ErrorRecentSwitchUndoFailed"] = "Could not restore the recent audio state: {0}",
        ["ErrorNoOverlayProfiles"] = "Create at least one profile with an output or input device before opening the overlay.",
        ["MessageConfigureBeforeToggle"] = "Configure the app before running toggle mode.",
        ["ToggleMissingDevices"] = "Both configured devices must be connected before switching. Missing: {0}.",
        ["ToggleSwitched"] = "Switched to {0}.",
        ["ToggleFailed"] = "Could not switch devices: {0}",
        ["MenuToggleNow"] = "Toggle now",
        ["MenuOpenSettings"] = "Open settings",
        ["MenuExit"] = "Exit",
        ["NotifyNoConfig"] = "No saved configuration was found.",
        ["IconDefault"] = "Default",
        ["UpdateStatusButton"] = "View update",
        ["UpdateDialogWindowTitle"] = "Update available",
        ["UpdateDialogTitle"] = "A new update is available",
        ["UpdateDialogMessage"] = "Version {0} has been published. Open the release page to download the latest build.",
        ["UpdateDialogCurrentVersion"] = "Current version: {0}",
        ["UpdateDialogLatestVersion"] = "Latest version: {0}",
        ["UpdateDialogPublishedAt"] = "Published: {0}",
        ["UpdateDialogPublishedUnknown"] = "Published date: unavailable",
        ["UpdateDialogOpenButton"] = "Open download page",
        ["UpdateDialogLaterButton"] = "Later",
        ["ShortcutStartupDescription"] = "Launch SoundDeviceSwitcher at sign-in.",
        ["ShortcutToggleDescription"] = "Toggle between the configured sound devices."
    };

    private readonly Dictionary<string, string> _korean = new(StringComparer.Ordinal)
    {
        ["AutomationGroup"] = "\uC790\uB3D9\uD654",
        ["AppName"] = "SoundDeviceSwitcher",
        ["SidebarMenuTitle"] = "메뉴",
        ["MainTab"] = "메인",
        ["SettingsTab"] = "설정",
        ["ActionsGroup"] = "빠른 작업",
        ["GeneralGroup"] = "일반",
        ["LanguageLabel"] = "언어",
        ["ThemeLabel"] = "테마",
        ["StartWithWindowsLabel"] = "Windows 시작 시 실행",
        ["StartMinimizedAtStartupLabel"] = "시스템 시작 시 최소화해서 실행",
        ["MinimizeToTrayOnCloseLabel"] = "닫을 때 트레이로 최소화",
        ["EnableUpdateNotificationsLabel"] = "앱 업데이트 알림 사용",
        ["SyncCommunicationDeviceWithPlaybackLabel"] = "\uC7AC\uC0DD-\uD1B5\uC2E0 \uC7A5\uCE58 \uC5F0\uB3D9",
        ["AutoSwitchToNewPlaybackDeviceLabel"] = "\uC0C8 \uC7A5\uCE58 \uC5F0\uACB0 \uC2DC \uC790\uB3D9 \uC804\uD658",
        ["OverlayGroup"] = "\uC624\uBC84\uB808\uC774",
        ["ProfilesGroup"] = "\uD504\uB85C\uD544",
        ["EnableProfilesLabel"] = "\uD504\uB85C\uADF8\uB7A8 \uC6B0\uC120\uC21C\uC704 \uAE30\uBC18 \uC790\uB3D9 \uC804\uD658",
        ["ProfileAutomationHint"] = "\uD65C\uC131 \uD504\uB85C\uADF8\uB7A8\uC5D0 \uB9DE\uB294 \uD504\uB85C\uD544\uC744 \uC790\uB3D9 \uC801\uC6A9\uD569\uB2C8\uB2E4. \uBAA9\uB85D\uC5D0\uC11C \uC704\uC5D0 \uC788\uB294 \uD504\uB85C\uD544\uC77C\uC218\uB85D \uC6B0\uC120\uC21C\uC704\uAC00 \uB192\uC2B5\uB2C8\uB2E4.",
        ["SwitchShortcutSectionLabel"] = "\uC7A5\uCE58 \uC804\uD658",
        ["EnableOverlayHotkeyLabel"] = "\uC624\uBC84\uB808\uC774 \uB2E8\uCD95\uD0A4 \uC0AC\uC6A9",
        ["OverlayShortcutSectionLabel"] = "\uC624\uBC84\uB808\uC774 \uB2E8\uCD95\uD0A4",
        ["RecentUndoSectionLabel"] = "최근 전환 되돌리기",
        ["EnableRecentSwitchUndoHotkeyLabel"] = "최근 전환 되돌리기 단축키 사용",
        ["ProfileNameLabel"] = "\uD504\uB85C\uD544 \uC774\uB984",
        ["ProfileIconLabel"] = "\uD504\uB85C\uD544 \uC544\uC774\uCF58",
        ["ProfilePriorityLabel"] = "\uC21C\uC11C",
        ["ProfileOutputDeviceLabel"] = "\uCD9C\uB825 \uC7A5\uCE58",
        ["ProfileInputDeviceLabel"] = "\uC785\uB825 \uC7A5\uCE58",
        ["ProfileProgramsLabel"] = "\uD504\uB85C\uADF8\uB7A8",
        ["OverlayPositionLabel"] = "\uC624\uBC84\uB808\uC774 \uC704\uCE58",
        ["OverlayLayoutLabel"] = "\uBC30\uC5F4 \uBC29\uD5A5",
        ["OverlayLayoutHorizontal"] = "\uAC00\uB85C",
        ["OverlayLayoutVertical"] = "\uC138\uB85C",
        ["OverlayHeightLabel"] = "\uC624\uBC84\uB808\uC774 \uB192\uC774 (\uD654\uBA74 \uB192\uC774 %)",
        ["OverlayHint"] = "\uC774 \uD398\uC774\uC9C0\uC758 \uD504\uB85C\uD544 \uBAA9\uB85D\uC744 \uADF8\uB300\uB85C \uC0AC\uC6A9\uD569\uB2C8\uB2E4. \uC624\uBC84\uB808\uC774 \uC704\uCE58, \uBC30\uC5F4, \uD06C\uAE30, \uB2E8\uCD95\uD0A4\uB97C \uC124\uC815\uD558\uC138\uC694.",
        ["OpenProfileOverlayButton"] = "\uC624\uBC84\uB808\uC774 \uC5F4\uAE30",
        ["ProfileOrderHint"] = "\uD504\uB85C\uADF8\uB7A8 \uC6B0\uC120\uC21C\uC704 \uAE30\uBC18 \uC790\uB3D9 \uC804\uD658\uC744 \uCF1C \uB450\uBA74 \uC704\uC5D0 \uC788\uB294 \uD504\uB85C\uD544\uC77C\uC218\uB85D \uBA3C\uC800 \uC801\uC6A9\uB429\uB2C8\uB2E4.",
        ["AddProfileButton"] = "\uD504\uB85C\uD544 \uCD94\uAC00",
        ["RemoveProfileButton"] = "\uD504\uB85C\uD544 \uC0AD\uC81C",
        ["MoveProfileUpButton"] = "\uC704\uB85C",
        ["MoveProfileDownButton"] = "\uC544\uB798\uB85C",
        ["AddProgramButton"] = "\uD504\uB85C\uADF8\uB7A8 \uCD94\uAC00",
        ["RemoveProgramButton"] = "\uD504\uB85C\uADF8\uB7A8 \uC0AD\uC81C",
        ["ProfileDefaultName"] = "\uD504\uB85C\uD544 {0}",
        ["ProfileUnnamed"] = "\uC774\uB984 \uC5C6\uB294 \uD504\uB85C\uD544",
        ["ProfileDoNotChangeOption"] = "\uBCC0\uACBD\uD558\uC9C0 \uC54A\uC74C",
        ["SelectProgramsDialogTitle"] = "\uD504\uB85C\uADF8\uB7A8 \uC2E4\uD589 \uD30C\uC77C \uC120\uD0DD",
        ["StatusProfileApplied"] = "\uD504\uB85C\uD544 \uC801\uC6A9: {0}",
        ["StatusRecentSwitchUndoApplied"] = "최근 오디오 장치 상태를 복원했습니다.",
        ["ErrorProfileMissingDevices"] = "\uD504\uB85C\uD544 '{0}'\uC744 \uC801\uC6A9\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. \uC0AC\uC6A9 \uBD88\uAC00 \uC7A5\uCE58: {1}",
        ["DeviceAIconLabel"] = "알림 아이콘",
        ["DeviceBIconLabel"] = "장치 B 아이콘",
        ["ThemeModeSystem"] = "시스템",
        ["ThemeModeLight"] = "라이트",
        ["ThemeModeDark"] = "다크",
        ["DevicesGroup"] = "장치",
        ["DeviceALabel"] = "장치 A",
        ["DeviceBLabel"] = "장치 B",
        ["HotkeyGroup"] = "단축키",
        ["EnableGlobalHotkey"] = "전역 단축키 사용",
        ["ModifiersLabel"] = "조합 키",
        ["KeyLabel"] = "키",
        ["HotkeyHint"] = "\uC571\uC774 \uC2E4\uD589 \uC911\uC77C \uB54C \uC0AC\uC6A9\uD560 \uB2E8\uCD95\uD0A4\uB97C \uC124\uC815\uD558\uC138\uC694. \uC804\uC5ED \uB2E8\uCD95\uD0A4\uB294 \uD2B8\uB808\uC774\uC5D0 \uC228\uACA8\uC838 \uC788\uC5B4\uB3C4 \uB3D9\uC791\uD569\uB2C8\uB2E4.",
        ["ShortcutCapturePlaceholder"] = "여기를 클릭하고 원하는 단축키를 누르세요",
        ["RecentSwitchUndoHint"] = "가장 최근의 출력, 입력 또는 통신 장치 변경 후 5초 이내에 누르면 이전 상태와 현재 상태를 서로 전환합니다.",
        ["ToggleNowButton"] = "지금 전환",
        ["RefreshDevicesButton"] = "장치 새로고침",
        ["OpenIconFolderButton"] = "아이콘 폴더 열기",
        ["RefreshIconsButton"] = "아이콘 새로고침",
        ["CreateToggleShortcutButton"] = "토글 바로가기 만들기",
        ["InitialStatus"] = "재생 장치 두 개를 선택하세요. 변경 내용은 자동으로 저장됩니다.",
        ["LoadedSavedSettings"] = "저장된 설정을 불러왔습니다.",
        ["NoSavedSettings"] = "저장된 설정이 없습니다. 장치 두 개를 선택해서 시작하세요.",
        ["StatusSettingsSaved"] = "설정을 저장했습니다.",
        ["StatusCreatedShortcut"] = "토글 바로가기를 만들었습니다: {0}",
        ["StatusLanguageChanged"] = "언어를 바꿨습니다.",
        ["StatusThemeChanged"] = "테마를 바꿨습니다.",
        ["StatusUpdateAvailable"] = "새 업데이트가 있습니다: {0}",
        ["StatusMinimizedToTray"] = "앱이 시스템 트레이에서 계속 실행 중입니다.",
        ["StatusOpenedIconFolder"] = "아이콘 폴더를 열었습니다.",
        ["StatusIconsRefreshed"] = "기본 및 사용자 아이콘 폴더에서 아이콘 {0}개를 다시 불러왔습니다.",
        ["StatusNoIconsFound"] = "기본 또는 사용자 아이콘 폴더에서 선택할 수 있는 아이콘을 찾지 못했습니다.",
        ["ErrorNeedTwoPlaybackDevices"] = "계속하려면 재생 장치 두 개 이상이 연결되어 있어야 합니다.",
        ["ErrorPrimarySecondaryDifferent"] = "장치 A와 장치 B는 서로 달라야 합니다.",
        ["ErrorEnableModifier"] = "단축키를 사용하려면 보조 키를 하나 이상 선택하세요.",
        ["ErrorNoConfig"] = "저장된 설정이 없습니다. 앱을 열어 장치를 먼저 설정하세요.",
        ["ErrorCouldNotLoadConfig"] = "저장된 설정을 불러오지 못했습니다: {0}",
        ["ErrorEmptyConfig"] = "저장된 설정 파일이 비어 있습니다.",
        ["ErrorCouldNotReadAudioDevices"] = "Windows 오디오 장치를 읽지 못했습니다. HRESULT: {0}. {1}",
        ["ErrorAppCouldNotLoad"] = "앱을 정상적으로 불러오지 못했습니다.",
        ["ErrorGlobalHotkeyUnavailable"] = "단축키를 등록하지 못했습니다. 다른 앱이 이미 사용 중일 수 있습니다.",
        ["ErrorRecentSwitchUndoUnavailable"] = "되돌릴 수 있는 최근 장치 변경이 없습니다.",
        ["ErrorRecentSwitchUndoExpired"] = "최근 장치 변경은 5초 이내에만 되돌릴 수 있습니다.",
        ["ErrorRecentSwitchUndoMissingDevices"] = "다음 장치가 없어 최근 오디오 상태를 복원할 수 없습니다: {0}",
        ["ErrorRecentSwitchUndoFailed"] = "최근 오디오 상태 복원에 실패했습니다: {0}",
        ["MessageConfigureBeforeToggle"] = "토글 모드를 사용하기 전에 앱을 먼저 설정하세요.",
        ["ToggleMissingDevices"] = "설정한 두 장치가 모두 연결되어 있어야 전환할 수 있습니다. 누락: {0}.",
        ["ToggleSwitched"] = "{0}(으)로 전환했습니다.",
        ["ToggleFailed"] = "장치 전환 실패: {0}",
        ["MenuToggleNow"] = "지금 전환",
        ["MenuOpenSettings"] = "설정 열기",
        ["MenuExit"] = "종료",
        ["NotifyNoConfig"] = "저장된 설정이 없습니다.",
        ["IconDefault"] = "기본",
        ["UpdateStatusButton"] = "업데이트 보기",
        ["UpdateDialogWindowTitle"] = "업데이트 안내",
        ["UpdateDialogTitle"] = "새 업데이트가 있습니다",
        ["UpdateDialogMessage"] = "버전 {0}이(가) 배포되었습니다. 최신 빌드를 받으려면 릴리스 페이지를 여세요.",
        ["UpdateDialogCurrentVersion"] = "현재 버전: {0}",
        ["UpdateDialogLatestVersion"] = "최신 버전: {0}",
        ["UpdateDialogPublishedAt"] = "배포 시각: {0}",
        ["UpdateDialogPublishedUnknown"] = "배포 시각: 확인할 수 없음",
        ["UpdateDialogOpenButton"] = "다운로드 페이지 열기",
        ["UpdateDialogLaterButton"] = "나중에",
        ["ShortcutStartupDescription"] = "로그인 후 SoundDeviceSwitcher를 실행합니다.",
        ["ShortcutToggleDescription"] = "설정한 사운드 장치 사이를 전환합니다."
    };

    public LocalizationService()
    {
        CurrentLanguage = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ko", StringComparison.OrdinalIgnoreCase)
            ? AppLanguage.Korean
            : AppLanguage.English;
    }

    public AppLanguage CurrentLanguage { get; private set; }

    public void SetLanguage(AppLanguage language)
    {
        CurrentLanguage = language;
    }

    public string Get(string key)
    {
        var dictionary = CurrentLanguage == AppLanguage.Korean ? _korean : _english;
        if (dictionary.TryGetValue(key, out var value))
        {
            return value;
        }

        return _english.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public string Format(string key, params object[] args)
    {
        return string.Format(Get(key), args);
    }
}
